name             'addressbook'
maintainer       'Vikas Sakode'
maintainer_email 'vikass85@gmail.com'
license          'All rights reserved'
description      'Installs/Configures addressbook'
long_description 'Installs/Configures addressbook'
version          '0.1.0'

depends 'users'
depends 'sudo'
depends 'apt'
depends 'ntp'
depends 'tomcat'
depends 'java'
depends 'artifact'
depends 'java_ext'
depends 'nginx'
depends 'datadog'
depends 'newrelic'
depends 'logrotate'
depends 'artifact'
